apps/recruiter/urls.py
# TALENTNEXT/apps/recruiter/urls.py

from django.urls import path
from . import views

app_name = 'recruiter'  # Correct namespacing

urlpatterns = [
    path('dashboard/', views.recruiter_dashboard, name='recruiter_dashboard'),
    path('profile/', views.recruiter_profile, name='recruiter_profile'),  # Profile URL
    path('jobs/', views.job_listing, name='job_listing'),
    path('jobs/create/', views.create_job, name='create_job'),
    path('jobs/<int:job_id>/', views.job_details, name='job_details'),
    path('applications/<int:application_id>/', views.view_application, name='view_application'),  # View Application URL
]

home/urls.py
# home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
]

templates/includes/footer.html
{% load static %}

<footer class="footer pt-5 mt-5">
  <div class="container">
      <div class="row">
          <div class="col-md-3 mb-4 ms-auto">
              <div>
                  <a href="https://www.creative-tim.com/product/material-kit-pro">
                      <img src="{% static 'img/logo-ct-dark.png' %}" class="mb-3 footer-logo" alt="main_logo">
                  </a>
                  <h6 class="font-weight-bolder mb-4">Material Kit 2 PRO</h6>
              </div>
              <div>
                  <ul class="d-flex flex-row ms-n3 nav">
                      <li class="nav-item">
                          <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">
                              <i class="fab fa-facebook text-lg opacity-8"></i>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                              <i class="fab fa-twitter text-lg opacity-8"></i>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                              <i class="fab fa-dribbble text-lg opacity-8"></i>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                              <i class="fab fa-github text-lg opacity-8"></i>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                              <i class="fab fa-youtube text-lg opacity-8"></i>
                          </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-md-2 col-sm-6 col-6 mb-4">
              <div>
                  <h6 class="text-sm">Company</h6>
                  <ul class="flex-column ms-n3 nav">
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                              About Us
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                              Freebies
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                              Premium Tools
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                              Blog
                          </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-md-2 col-sm-6 col-6 mb-4">
              <div>
                  <h6 class="text-sm">Resources</h6>
                  <ul class="flex-column ms-n3 nav">
                      <li class="nav-item">
                          <a class="nav-link" href="https://iradesign.io/" target="_blank">
                              Illustrations
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">
                              Bits & Snippets
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">
                              Affiliate Program
                          </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-md-2 col-sm-6 col-6 mb-4">
              <div>
                  <h6 class="text-sm">Help & Support</h6>
                  <ul class="flex-column ms-n3 nav">
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">
                              Contact Us
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">
                              Knowledge Center
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-material-kit-pro-footer" target="_blank">
                              Custom Development
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">
                              Sponsorships
                          </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
              <div>
                  <h6 class="text-sm">Legal</h6>
                  <ul class="flex-column ms-n3 nav">
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/terms" target="_blank">
                              Terms & Conditions
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/privacy" target="_blank">
                              Privacy Policy
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">
                              Licenses (EULA)
                          </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-12">
              <div class="text-center">
                  <p class="text-dark my-4 text-sm font-weight-normal">
                      &copy; <a href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> - coded by AppSeed.
                  </p>
              </div>
          </div>
      </div>
  </div>
</footer>

templates/includes/navigation.html
<!-- templates/includes/header.html -->

<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute mt-4 my-3 py-2 start-0 end-0 mx-4">
                <div class="container-fluid px-0">
                    <a class="navbar-brand font-weight-bolder ms-sm-3 d-none d-md-block" href="#">
                        JobNext
                    </a>
                    
                    <button class="navbar-toggler shadow-none ms-md-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon mt-2">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </span>
                    </button>
                    
                    <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0" id="navigation">
                        <ul class="navbar-nav navbar-nav-hover ms-auto">
                            <!-- Check if user is authenticated -->
                            {% if user.is_authenticated %}
                                <!-- Conditional display for 'candidate' role -->
                                {% if user.role == 'candidate' %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'candidate:candidate_dashboard' %}">
                                            Candidate Dashboard
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'candidate:my_jobs_status' %}">
                                            My Job Status
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'candidate:candidate_profile' %}">
                                            My Profile
                                        </a>
                                    </li>
                                {% endif %}
    
                                <!-- Conditional display for 'recruiter' role -->
                                {% if user.role == 'recruiter' %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'recruiter:recruiter_dashboard' %}">
                                            Recruiter Dashboard
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'recruiter:job_listing' %}">
                                            Jobs
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'recruiter:recruiter_profile' %}">
                                            My Profile
                                        </a>
                                    </li>
                                {% endif %}
                                
                                <!-- Logout button -->
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'authentication:signout' %}">
                                        Logout
                                    </a>
                                </li>
                            {% else %}
                                <!-- Links for non-authenticated users -->
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'authentication:signin' %}">
                                        Login
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'authentication:register_candidate' %}">
                                        Sign Up
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

templates/includes/scripts.html
{% load static %}
<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<!--  Plugin for TypedJS, full documentation here: https://github.com/mattboldt/typed.js/ -->
<script src="{% static 'js/plugins/typedjs.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/highlight.min.js' %}"></script>
<!--  Plugin for CountUp.js, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the blob animation -->
<script src="{% static 'js/plugins/anime.min.js' %}" type="text/javascript"></script>
<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
<script src="{% static 'js/material-kit-pro.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/glide.min.js' %}"></script>

<!-- for ajax -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>